// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ofbvDsTHLIS1z8Nw-G4EtnKxchN_kFY',
    appId: '1:489141037992:web:bce8ad442eded7efd7cb9d',
    messagingSenderId: '489141037992',
    projectId: 'musicplayer-e9b1c',
    authDomain: 'musicplayer-e9b1c.firebaseapp.com',
    storageBucket: 'musicplayer-e9b1c.appspot.com',
    measurementId: 'G-BVR4PBGQKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRVdxXq1lgNxnO7N8XTxcvPA1Aa6dWWQ',
    appId: '1:489141037992:android:0e7105209757e364d7cb9d',
    messagingSenderId: '489141037992',
    projectId: 'musicplayer-e9b1c',
    storageBucket: 'musicplayer-e9b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfz42GyuZSb2JCdbqj5I01_yCYAf0etU0',
    appId: '1:489141037992:ios:50d6d5827618df5ed7cb9d',
    messagingSenderId: '489141037992',
    projectId: 'musicplayer-e9b1c',
    storageBucket: 'musicplayer-e9b1c.appspot.com',
    iosClientId: '489141037992-rhbmjfd7sj19n72dgvctk97ej29o8eq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfz42GyuZSb2JCdbqj5I01_yCYAf0etU0',
    appId: '1:489141037992:ios:50d6d5827618df5ed7cb9d',
    messagingSenderId: '489141037992',
    projectId: 'musicplayer-e9b1c',
    storageBucket: 'musicplayer-e9b1c.appspot.com',
    iosClientId: '489141037992-rhbmjfd7sj19n72dgvctk97ej29o8eq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicPlayer',
  );

}